/**
 * Independent Delhivery API Integration
 * Requires DELHIVERY_API_KEY in .env.local
 */

const BASE_URL = "https://track.delhivery.com/api";

function getHeaders() {
  const apiKey = process.env.DELHIVERY_API_KEY;
  if (!apiKey) {
    throw new Error("Missing DELHIVERY_API_KEY in environment variables.");
  }
  return {
    "Content-Type": "application/json",
    "Authorization": `Token ${apiKey}`
  };
}

// 1. Create Order (Waybill)
export async function createDelhiveryOrder(orderData: any) {
  // Format standard Marbie order data into Delhivery's required package format
  const payload = {
    format: "json",
    data: {
      shipments: [
        {
          name: orderData.billing_customer_name,
          add: orderData.billing_address,
          pin: orderData.billing_pincode,
          city: orderData.billing_city,
          state: orderData.billing_state,
          country: "India",
          phone: orderData.billing_phone,
          order: orderData.order_id,
          payment_mode: orderData.payment_method === "Prepaid" ? "Pre-paid" : "COD",
          return_pin: "394230", // Replace with real Marbie return pincode
          return_city: "Surat",
          return_phone: "9876543210",
          return_add: "Marbie Warehouse",
          return_state: "Gujarat",
          return_country: "India",
          products_desc: "Jewelry",
          hsn_code: "711319",
          cod_amount: orderData.payment_method === "COD" ? orderData.sub_total : 0,
          order_date: orderData.order_date,
          total_amount: orderData.sub_total,
          seller_add: "Marbie Warehouse",
          seller_name: "Marbie Jewels",
          seller_inv: `INV-${orderData.order_id}`,
          quantity: "1",
        }
      ],
      pickup_location: {
        name: "Marbie Primary Location",
        add: "Marbie Warehouse, Surat",
        city: "Surat",
        pin: "394230",
        country: "India",
        phone: "9876543210"
      }
    }
  };

  const res = await fetch(`${BASE_URL}/cmu/create.json`, {
    method: "POST",
    headers: getHeaders(),
    body: JSON.stringify(payload)
  });

  if (!res.ok) {
    console.error("Delhivery API Failed:", await res.text());
    throw new Error("Failed to create order in Delhivery");
  }

  const responseData = await res.json();
  
  if (!responseData.success && !responseData.packages?.length) {
      throw new Error("Delhivery Order Creation Failed: " + JSON.stringify(responseData));
  }
  
  // Return the waybill (AWB) number generated by Delhivery
  return {
    success: true,
    awb_code: responseData.packages[0].waybill,
    courier_name: "Delhivery"
  };
}
